version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "SA", "-P", "$$MSSQL_SA_PASSWORD", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    volumes:
      - sqlserver-data:/var/opt/mssql

  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./sql:/sql:ro
    environment:
      DB_HOST: sqlserver
      DB_USER: sa
      DB_PASSWORD: "YourStrong@Passw0rd"
    entrypoint: ["/bin/bash", "/sql/init-db.sh"]

  api:
    build: .
    environment:
      PORT: 3000
      DB_HOST: sqlserver
      DB_USER: sa
      DB_PASSWORD: "YourStrong@Passw0rd"
      DB_NAME: ClientesDb
    ports:
      - "3000:3000"
    depends_on:
      sqlserver:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully

volumes:
  sqlserver-data:
