version: "3.9"

services:

  container-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        -  ../..:/workspaces:cached
    network_mode: rede-app
    

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: workspace-sqlserver
    restart: unless-stopped
    network_mode: rede-app

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassword!123"
      MSSQL_PID: "Developer"    
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  mongodb:
    image: mongo:6.0
    container_name: workspace-mongodb
    restart: unless-stopped
    network_mode: rede-app
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  sqlserver-data:
  mongodb-data:

  
networks: 
 rede-app:
